# 1. Imagem Base
FROM php:8.3-fpm-alpine

# Define o diretório de trabalho
WORKDIR /var/www/html

# 2. Instalação de Dependências PHP e Ferramentas do Sistema
# Adiciona ferramentas de build, dependências PHP e curl
RUN apk update && apk add --no-cache \
    $PHPIZE_DEPS \
    git \
    zip \
    unzip \
    libzip-dev \
    libpng-dev \
    libxml2-dev \
    curl \
    # Instala o PHP para DB, imagens, XML e OPcache
    && docker-php-ext-install pdo_mysql gd exif opcache

# 3. Instalação do Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# 4. Instalação do Node.js/NPM
# Baixa e instala a versão LTS do Node.js (v20.x)
RUN curl -sL https://unofficial-builds.nodejs.org/download/release/v20.10.0/node-v20.10.0-linux-x64-musl.tar.xz | tar -xJ --strip-components=1 -C /usr/local \
    && rm -rf /var/cache/apk/*

# 5. Configuração Final
EXPOSE 9000

# Permissões (chown)
RUN chown -R www-data:www-data /var/www/html

# Comando padrão para iniciar o PHP-FPM
CMD ["php-fpm"]